experiment_name: gantext_random_seed_cuda
description: Running a basic GAN agent for text generation. LSTM for G and GRU for D.
agent: GANTextAgent
mode: train
cuda: True
gpu_device: 0
seed: -1
g_input_size: 100
num_classes: 2
max_seq_len: 100
context_size: 2
embedding_size: 100
hidden_size: 32
num_epochs: 1
batch_size: 8
num_layers: 2
bidirectional: True
learning_rate: 3e-4
beta1: 0.9
beta2: 0.999
dropout_prob: 0.2
log_dir: /runs/gantext/
validate_every: 4
checkpoint_dir: /savedmodels/gantext/
checkpoint_file: base_version.pth
dataloader: WikiText2DL
generator: Generator
discriminator: Discriminator
dl_workers: 1
process_data: True
